language: python
python:
- '2.7'
- '3.4'
- '3.5'
- '3.6'
install:
- pip install .
script: pytest
deploy:
  provider: pypi
  user: kchen
  password:
    secure: L8uHglgU3vzBsrlCGA2tzVG16tNDQnlxQn6WoXg8udjFO2QhRDl6mTPnVUGsKL4JwrTRIlBri4cd46o87EjsincxLk8tVWjCAW1iQNvOt3wBDxDpoDvhyAWb679QDoUcaZVuQyNJYMEdhU32OuVp7/5uBMZ6gofmbKxTTjpmAvRExa3M5EoLJoq0Mff4feHiLbvAuTEAatpAxzaBrhsO7fKE8xsTEdMGPVZ4isTG5ZdmBNALMWhaGy0e7TrvY6etgH8RLFuVI19BcJ9Oq3nNP6A/yat1i5+taNTA4lJYRVXdwucMs1arFoMC0E/wJhwQHPM6cm11fmu68ZdS4xw/Ad2xJgjqUFCN7SvXxv0mxz2tleFExos45M6Mnh+3OpMwsq9Lg4DtZw5oVhDE40YkJyMYLPZpTkrwxZKXvpQiqxndxQqR2uVZLkWUBnfbvBKyAeAWrMpwyt3zSzRyp1tLAw7XPh5q1Q1vRg48HK7yN62ElvxqUkC8TalyZfgUvj1+nYoX9vN/bfrifhrzTOm7HUOOm+lGEdu6FGOC+qo8pV6lp8VTuVvkLhLrQA4W0EaxkB0CqUCmAyBJCecgAXOcx70pD+sUJBgLEMn5t4xQdfoh3V1B6EclVhjcixozWv11hnVqw7DVRoDN717VK1/RqYk0FQTXQPyChVivVgXXeFk=
  on:
    branch: master
    tags: true
    python: '3.5'
  distributions: sdist bdist_wheel
  skip_cleanup: true
  skip_upload_docs: true
