language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

install:
  - pip install .

script: pytest

deploy:
  provider: pypi
  user: kchen
  password:
    secure: FxdvBxjCGG+nQTMNnNBHkDLL5OPtFtL8FVR1EATs2kvkMPgo73ukoAZq0IE1J+WN0ZU3tvYb/3khVt+1Z9iNIll3yDcaE4nf5joIjGjAUk4Gj6FxceFSVGdqb2TQ83HspLMi14CsBRJKm+azpjXsWg6BqP/Hv54Lb1JokkszNettbmaAyOyBPlwjWPWgu1DTgr2HD0maDjFF2xAEn38QOUfOnuOlMRaxu9DrggIp5m5Jvn7bg/fak6bnZ1oyOQoAv4WSWk2CbFa1kqMhX4lROyIts34GhIN81xstBBXtr+lpsNljADcz+P0Gg7KDq5la2+fq1A4pW8slMShU/56Bp5xrsMd/AEl5p2uElh5WC50gG9xuXxBZGVvM8NlepaQM7G+e/o8cAcIylrVZCjS9NLPPyss1/9dkElmfhVP4RJ3ozT+kX3sDjxbEBCfnPAgEpfZN9ubCpWT737SnIdJJGi1z9yMl0P+k50E1hCIBQGPQuiAReR4fjKq29wl+n/GR5aQ5k66tEwMinMU/WFddy78gB+HLU2C/MZF5OCWvW0tuS0rouAI9DMonTxWJlBKMg3t7owlM1xCHt5LuQclqjp9TMiZp600Y20YHxt8iFW8zsidE/Xc0fZ9JG9LXc1/u+1Fdt5cmJNJ2DR/FG3442q8Fh6Z6YOrkzd+ZPzYLlhA=
  on:
    branch: master
    tags: true
    python: "3.5"
  distributions: sdist bdist_wheel
  skip_cleanup: true
  skip_upload_docs: true
